### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by instruccionesaldorso**
@Nostrabramus I improved some stuff:
- Remove empty files (if nothing is there for Extbase, you can skip its creation).
- Rename TypoScript files according to new standards.
- Use localization service from TYPO3, and you don't have to take care of prefixes for locallang.xlf files. Just having them in place will allow TYPO3 to search for the labels there directly.

### CODE REVIEW

**Comment by instruccionesaldorso** [comment]
It is good that you have under ext_emconf.php file a psr-4 section for composer installations auto-detect your class.

**Comment by instruccionesaldorso** [comment]
By the way, your version from TER has a "MACOSX" folder on the root, it would be nice to remove it.

**Comment by Nostrabramus** [comment]
Thanks a lot @instruccionesaldorso,
we are reviewing it

**Review by Nostrabramus — APPROVED** [review]
renaming typoscript files

**Review by Nostrabramus — APPROVED** [review]
Deletes empty ext_tables.sql

**Review by Nostrabramus — APPROVED** [review]
Deletes empty ext_tables.php

**Review by Nostrabramus — APPROVED** [review]
Changes management of localization.

**Pull request merged**
